package com.incluctab.tddClasses.eStore;

public enum State {
    ABIA, ADAMAWA, AKWAIBOM, ANAMBRA, BAUCHI,
    BAYELSA, BENUE, BORNO, CROSSRIVER, DELTA,
    EBONYI, EDO, EKITI, ENUGU, GOMBE, IMO, JIGAWA,
    KADUNA, KANO, KATSINA, KEBBI, KOGI, KWARA,
    LAGOS, NASARAWA, NIGER, OGUN, ONDO, OSUN,
    OYO, PLATEAU, RIVERS, SOKOTO, TARABA, YOBE,
    ZAMFARA
}
